### ISSUE TITLE
How to get selected photo?

### ISSUE THREAD

**Issue by felipecaldas** [jeancsanchez/PhotoViewSlider#1]
Hey there Jean,

Thanks for the library, it's pretty cool.

Is there a way to know which photo was selected by the user? I tap on the image, it gets focus on screen but I'd like now to either display a button in there so the user can use the photo or somehow find out which photo was selected.

Is this possible?

Thanks!

**Comment by jeancsanchez** [comment]
Hello Felipe! 😀

For while the library does not support getting the current photo clicked by the user :/ 
Maybe it can be a future feature on the next version. Feel free to send PR if you have a better solution for this problem.
