### ISSUE TITLE
Clean the Component

### ISSUE THREAD

**Issue by dwane161** [jeancsanchez/PhotoViewSlider#2]
I had a question, how can i clean the component, for reuse that again?

**Comment by jeancsanchez** [comment]
What you mean with "clean a component" exactly?

**Comment by dwane161** [comment]
Erase all the photos, and reuse them!

**Comment by jeancsanchez** [comment]
Ok. On the moment, no there is a way for to do it.  I will make this feature on the next version. Or if you prefer, you can send me a PR. Thanks  :)
